"""
DeepTrace Graph State Definition

This module defines the central state object that is passed between agents
in the LangGraph workflow. It acts as the shared memory for the entire research process.
"""

from typing import TypedDict, List, Dict, Any, Annotated
import operator

# ==========================================
# RULE 1: WHAT IS THIS CONCEPT?
# ==========================================
# LangGraph State is essentially a shared clipboard or a baton in a relay race.
# As our multi-agent system runs, each agent (Planner, Search, Critic, Writer)
# needs to know what the previous agents have done.
#
# TypedDict ensures that this "clipboard" has a strict structure. It guarantees
# that every agent knows exactly what keys exist in the dictionary and what
# data types they contain.
#
# Annotated[List[Any], operator.add] is a special LangGraph concept called a "reducer".
# Normally, if Node A returns {"sources": ["A.com"]} and Node B returns
# {"sources": ["B.com"]}, Node B overwrites Node A.
# With `operator.add`, LangGraph appends them instead: ["A.com", "B.com"].

class ResearchState(TypedDict):
    """
    Represents the state of our DeepTrace research graph.

    Fields:
    - run_id: UUID4 string generated once per main() execution. Used to tag all
      Qdrant documents stored in this run, enabling retrieval isolation from
      documents produced by other runs. Never changes during a run.
    - query: The exact question the user asked. Never changes once set.
    - sub_questions: Generated by the Planner. A list of broken-down questions to search for.
    - search_results: Accumulated context and findings from the Search & VectorDB.
      We use `operator.add` so each search iteration appends new findings rather than overwriting.
    - sources: Accumulated list of unique URLs or document IDs referenced during research.
    - iteration_count: Tracks how many times we've looped through the search/critic cycle.
      Crucial for preventing infinite loops.
    - critic_feedback: If the Critic rejects the findings, it puts its reasoning here
      so the Planner/Search can adjust.
    - quality_score: A numerical score (e.g., 0.0 to 1.0) assigned by the Critic or Evaluator.
    - is_valid: A boolean flag set by the Critic to determine routing (True -> Writer, False -> back to Search)
    - status: A human-readable string indicating current phase (e.g., "planning", "searching", "writing", "failed")
    - report: The final synthesized markdown generated by the Writer.
    - errors: Accumulated list of runtime errors, API failures, or fallback events.
    """

    # Phase 4B: UUID4 generated once per run. Tags all Qdrant payloads for run-level isolation.
    run_id: str

    # The raw input from the user (e.g., "Future of Quantum Computing")
    query: str

    # Planner agent populates this (e.g., ["Hardware limits", "Algorithm breakthroughs"])
    sub_questions: List[str]

    # Search agent appends findings here.
    # Example item: {"question": "...", "snippet": "...", "content": "..."}
    # Using operator.add prevents overwriting past research in a loop.
    search_results: Annotated[List[Dict[str, Any]], operator.add]

    # Generated by the Query Optimizer during a retry loop
    retry_queries: List[str]

    # Highly curated, semantically relevant snippets pulled from Qdrant.
    # The Writer Agent uses this filtered list instead of the raw search_results.
    retrieved_documents: List[Dict[str, Any]]

    # Accumulated URLs or document references. Appended across iterations.
    sources: Annotated[List[str], operator.add]

    # Loop counter to prevent infinite loops during Critic validation
    iteration_count: int

    # Critic agent explains why the data is bad (if it is)
    critic_feedback: str

    # Numerical evaluation of the current state of findings.
    quality_score: float

    # Flag to control the conditional edge (True = go to Writer, False = go back to Search)
    is_valid: bool

    # Tracking the current phase for observability and UI updates.
    status: str

    # Writer agent places the final markdown here
    report: str

    # Non-fatal errors or warnings appended during execution.
    errors: Annotated[List[str], operator.add]

    # Flag to indicate if the system has hit max retries and needs to gracefully degrade.
    degradation_mode: bool


# ==========================================
# HOW FUTURE AGENTS WILL UPDATE IT (EXAMPLE)
# ==========================================
#
# 1. INITIALIZATION:
# state = ResearchState(
#     run_id="a3f2c1d4-...",        # <-- NEW: generated once in main()
#     query="Future of Quantum Computing",
#     sub_questions=[],
#     search_results=[],
#     sources=[],
#     iteration_count=0,
#     critic_feedback="",
#     quality_score=0.0,
#     is_valid=False,
#     status="initialized",
#     report="",
#     errors=[]
# )
#
# 2. PLANNER NODE executes and returns a partial dictionary.
# LangGraph automatically merges this into the main state:
# return {
#     "sub_questions": ["What is Qubit scaling?", "Error correction methods?"],
#     "status": "planning_complete"
# }
#
# 3. SEARCH NODE executes, finds info, and returns:
# return {
#     "search_results": [{"snippet": "Scaling requires cold temps..."}],
#     "sources": ["ibm.com/quantum"],
#     "iteration_count": state["iteration_count"] + 1,
#     "status": "searching_complete"
# }
# *Note:* Because of `operator.add`, the lists are *appended* to existing state.
#
# 4. CRITIC NODE executes, assesses the quality, and decides routing:
# return {
#     "is_valid": True,
#     "quality_score": 0.95,
#     "status": "validation_passed"
# }
#
# 5. WRITER NODE executes:
# return {"report": "# Quantum Computing\n...", "status": "completed"}
