"""
Planner Agent for DeepTrace

This module defines the Planner Node. Its responsibility is to take a broad
research query and break it down into exactly 5 focused, actionable sub-questions.
"""

from typing import Dict, Any
from langchain_core.prompts import PromptTemplate
from langchain_core.output_parsers import PydanticOutputParser
from pydantic import BaseModel, Field
from app.graph.state import ResearchState
from app.core.llm import get_llm

# ==========================================
# RULE 1: WHAT IS THIS CONCEPT?
# ==========================================
# The Planner Agent is the "architect" of our research process.
# 
# Why planning improves retrieval quality:
# Without planning:
# User Query -> One broad search -> Mixed results -> Lower report quality
# 
# With planning:
# User Query -> 5 focused sub-questions -> 5 focused searches -> 
# Better coverage -> Better retrieval quality -> Better final report
#
# We mandate that the LLM must "Return JSON format from LLM". We enforce 
# and validate this using "Pydantic output parsing".

# 1. Define the desired output structure using Pydantic
class SubQuestions(BaseModel):
    """Schema for the expected output from the Planner LLM."""
    questions: list[str] = Field(
        description="Exactly 5 research-focused sub-questions derived from the main query."
    )

def planner_node(state: ResearchState) -> Dict[str, Any]:
    """
    Executes the planning phase of the research workflow.
    
    Args:
        state: The current ResearchState containing the original 'query'.
        
    Returns:
        A dictionary containing the generated 'sub_questions', 'status', 
        and optionally 'errors' to be merged into the main state.
    """
    
    query = state.get("query", "")
    
    # Defensive check: if there's no query, we can't plan.
    if not query:
        return {
            "errors": ["Planner received an empty query."],
            "status": "planning_failed"
        }

    # 2. Set up the Pydantic Output Parser
    parser = PydanticOutputParser(pydantic_object=SubQuestions)

    # 3. Prompt Engineering
    # We provide the format instructions directly generated by the parser.
    # This instructs the LLM on the exact JSON schema it must adhere to.
    prompt = PromptTemplate(
        template="""You are an expert research planner. 
Your task is to break down the user's overarching research query into EXACTLY 5 distinct, highly-focused sub-questions.
These sub-questions should cover different angles of the topic (e.g., technical, historical, future outlook, economic impact, etc.) to ensure comprehensive research.

User Query: {query}

{format_instructions}

Return ONLY the valid JSON object. Do not include any introductory or concluding text. Do not use markdown code blocks, just output the raw JSON.
""",
        input_variables=["query"],
        partial_variables={"format_instructions": parser.get_format_instructions()},
    )

    # 4. Initialize the LLM using our centralized, fault-tolerant configuration
    llm_config = get_llm()
    robust_llm = llm_config["llm"]

    # 5. Create the execution chain
    chain = prompt | robust_llm | parser

    try:
        # Execute the chain
        # The chain will: format prompt -> call LLM -> parse JSON output into Pydantic model
        result: SubQuestions = chain.invoke({"query": query})
        
        # Validate EXACTLY 5 sub-questions.
        # We do NOT silently truncate. We raise a ValueError to trigger failure handling
        # so the system doesn't proceed with malformed intent.
        if len(result.questions) != 5:
            raise ValueError(f"Expected exactly 5 questions, got {len(result.questions)}")
        
        return {
            "sub_questions": result.questions,
            "status": "planning_complete"
        }
        
    except Exception as e:
        # Error handling: If parsing fails (e.g., LLM returned bad JSON), 
        # validation fails (wrong number of questions), or API fails (all fallbacks exhausted)
        error_msg = f"Planner failed: {str(e)}"
        return {
            "errors": [error_msg],
            "status": "planning_failed",
            "sub_questions": [] # Return empty list so downstream nodes don't crash on None
        }

# ==========================================
# CONNECTING THE DOTS
# ==========================================
# How this planner connects to the ecosystem:
# - LangGraph State: It reads state["query"] and updates state["sub_questions"] 
#   and state["status"].
# - Search Agent: The Search Agent will loop through the generated state["sub_questions"]
#   and perform a distinct web search for each one.
# - Future Critic Agent: If the Search Agent's findings are poor, the Critic 
#   will review these original sub_questions to see if the plan itself was flawed.

# ==========================================
# EXAMPLE INPUT / OUTPUT
# ==========================================
# Input State:
# {"query": "The impact of artificial intelligence on modern healthcare"}
#
# Expected Return Dictionary:
# {
#     "sub_questions": [
#         "How are AI algorithms currently being utilized in diagnostic imaging and early disease detection?",
#         "What are the ethical and privacy concerns surrounding patient data in AI-driven healthcare systems?",
#         "In what ways is artificial intelligence accelerating pharmaceutical research and drug discovery?",
#         "How is AI being used to personalize treatment plans and patient care pathways?",
#         "What are the economic impacts and cost-saving potentials of integrating AI into hospital administration?"
#     ],
#     "status": "planning_complete"
# }
