"""
Search Agent for DeepTrace

This module defines the Search Node. Its responsibility is to take the 
sub-questions generated by the Planner and execute web searches to retrieve 
factual, up-to-date, structured information for each question.
"""

import re
from typing import Dict, Any, List
from langchain_community.utilities import DuckDuckGoSearchAPIWrapper
from app.graph.state import ResearchState

# ==========================================
# RULE 1: WHAT IS THIS CONCEPT?
# ==========================================
# The Search Agent executes the retrieval phase of our pipeline.
#
# PHASE 3 UPGRADE: Feedback-Aware Retries
# In Phase 2, this agent was linear. In Phase 3, it is cyclic.
# If the Critic node finds the research insufficient, it routes back here.
# Instead of repeating the same searches, this agent now checks 'critic_feedback'
# and generates new, targeted search queries using deterministic Python logic.

def generate_retry_queries(original_query: str, feedback: str) -> List[str]:
    """
    Deterministic keyword extraction from Critic feedback. 
    Strips editorial filler and constructs natural search queries.
    """
    # 1. Strip common 'Editorial Filler' phrases often used by the Critic LLM
    editor_filler = [
        "coverage is missing", "research lacks", "missing", 
        "need more data on", "provide more on", "information about",
        "please include", "the documents are", "low score because"
    ]
    
    cleaned_feedback = feedback.lower()
    for phrase in editor_filler:
        cleaned_feedback = cleaned_feedback.replace(phrase, "")

    # 2. Extract alphanumeric words and filter out common stop words
    # This leaves only the 'Signal' keywords (nouns/topics)
    words = re.findall(r'\w+', cleaned_feedback)
    
    stop_words = {
        "is", "are", "the", "a", "an", "and", "on", "about", 
        "for", "with", "of", "in", "to", "it", "was", "were"
    }
    
    # Filter keywords: must not be a stop word and length > 2
    keywords = [w for w in words if w not in stop_words and len(w) > 2]
    
    # Deduplicate while preserving order
    unique_keywords = []
    for k in keywords:
        if k not in unique_keywords:
            unique_keywords.append(k)

    # 3. Construct Queries: Use the Top 3 extracted keywords
    # Format: [Original Query] [Keyword]
    retry_queries = []
    for kw in unique_keywords[:3]:
        retry_queries.append(f"{original_query} {kw}")

    # 4. Safety Fallback: If feedback was too short or non-extractable
    if not retry_queries:
        retry_queries.append(f"{original_query} detailed analysis")

    return retry_queries

def search_node(state: ResearchState) -> Dict[str, Any]:
    """
    Executes the web search phase of the research workflow.
    
    Args:
        state: The current ResearchState containing 'sub_questions' and 'iteration_count'.
        
    Returns:
        A dictionary containing the structured 'search_results', extracted 'sources', 
        'errors' (if any), 'iteration_count' (incremented), and a granular 'status' 
        to be merged into the main state.
    """
    
    query = state.get("query", "")
    sub_questions = state.get("sub_questions", [])
    current_iteration = state.get("iteration_count", 0)
    feedback = state.get("critic_feedback", "")
    
    # PHASE 3 LOGIC: Determine which queries to run
    # If this is a retry (iteration > 0), we use the feedback to pivot.
    if current_iteration > 0 and feedback:
        print(f"[Search] Retry cycle {current_iteration}. Refining search based on Critic feedback...")
        queries_to_run = generate_retry_queries(query, feedback)
    else:
        # Initial run: Use the planner's sub-questions
        queries_to_run = sub_questions

    # Defensive check
    if not queries_to_run:
        return {
            "errors": ["Search Agent received no queries to execute."],
            "status": "search_failed",
            "iteration_count": current_iteration + 1
        }

    # Initialize the native API wrapper.
    search_tool = DuckDuckGoSearchAPIWrapper()
    
    # Accumulators for our state updates
    accumulated_results = []
    accumulated_sources = []
    accumulated_errors = []
    
    success_count = 0

    # Process: Loop through all determined queries
    for q in queries_to_run:
        try:
            # Run the search
            raw_results = search_tool.results(q, max_results=3)
            
            if not isinstance(raw_results, list) or not raw_results:
                 accumulated_errors.append(f"No valid results found for: '{q}'")
                 continue
                 
            success_count += 1

            for item in raw_results:
                if not isinstance(item, dict):
                    continue
                    
                # Store the structured result
                accumulated_results.append({
                    "question": q,
                    "title": item.get("title", ""),
                    "snippet": item.get("snippet", ""),
                    "source": item.get("link", "")
                })
                
                if item.get("link"):
                    accumulated_sources.append(item.get("link"))
                
        except Exception as e:
            error_msg = f"Search failed for query '{q}': {str(e)}"
            accumulated_errors.append(error_msg)

    # Determine status
    status = "search_complete" if success_count > 0 else "search_failed"

    # LangGraph will use `operator.add` to append these results to the global state.
    # We increment the iteration count to maintain the loop safety valve.
    return {
        "search_results": accumulated_results,
        "sources": list(set(accumulated_sources)),
        "errors": accumulated_errors,
        "status": status,
        "iteration_count": current_iteration + 1
    }
