"""
Search Agent for DeepTrace

This module defines the Search Node. Its responsibility is to take the
sub-questions generated by the Planner and execute web searches to retrieve
factual, up-to-date, structured information for each question.

Phase 4B Update:
The Search Agent no longer depends directly on DuckDuckGoSearchAPIWrapper.
It obtains its search provider through get_search_provider(), which returns
a ChainedSearchProvider (Tavily primary → DuckDuckGo fallback). The agent
is unaware of which concrete provider is active.
"""

from typing import Dict, Any, List
from app.graph.state import ResearchState
from app.search import get_search_provider

# ==========================================
# RULE 1: WHAT IS THIS CONCEPT?
# ==========================================
# The Search Agent executes the retrieval phase of our pipeline.
#
# PHASE 3 UPGRADE: Feedback-Aware Retries
# In Phase 2, this agent was linear. In Phase 3, it is cyclic.
# If the Critic node finds the research insufficient, it routes back here.
# In Phase 3B, it reads 'retry_queries' populated by the Query Optimizer.
#
# PHASE 4B UPGRADE: Provider Abstraction
# The agent no longer directly calls DuckDuckGo. It delegates to whatever
# SearchProvider is configured (currently Tavily → DuckDuckGo chain).

def search_node(state: ResearchState) -> Dict[str, Any]:
    """
    Executes the web search phase of the research workflow.

    Args:
        state: The current ResearchState containing 'sub_questions' and 'iteration_count'.

    Returns:
        A dictionary containing the structured 'search_results', extracted 'sources',
        'errors' (if any), 'iteration_count' (incremented), and a granular 'status'
        to be merged into the main state.
    """

    query = state.get("query", "")
    sub_questions = state.get("sub_questions", [])
    current_iteration = state.get("iteration_count", 0)
    retry_queries = state.get("retry_queries", [])

    # PHASE 3 LOGIC: Determine which queries to run
    # If this is a retry (iteration > 0) and we have optimized queries, use them.
    if current_iteration > 0 and retry_queries:
        print(f"[Search] Retry cycle {current_iteration}. Refining search based on Query Optimizer...")
        queries_to_run = retry_queries
    else:
        # Initial run: Use the planner's sub-questions
        queries_to_run = sub_questions

    # Defensive check
    if not queries_to_run:
        return {
            "errors": ["Search Agent received no queries to execute."],
            "status": "search_failed",
            "iteration_count": current_iteration + 1
        }

    # PHASE 4B: Obtain the configured provider chain (Tavily → DuckDuckGo fallback).
    # The provider is instantiated once here and reused across all queries in this
    # cycle, avoiding repeated client initialization overhead.
    provider = get_search_provider()
    print(f"[Search] Using provider: {provider.name}")

    # Accumulators for our state updates
    accumulated_results = []
    accumulated_sources = []
    accumulated_errors = []

    success_count = 0

    # Process: Loop through all determined queries
    for q in queries_to_run:
        try:
            # Delegate to the provider — returns normalized List[Dict] or []
            raw_results = provider.search(q)

            if not raw_results:
                accumulated_errors.append(f"No valid results found for: '{q}'")
                continue

            success_count += 1

            for item in raw_results:
                if not isinstance(item, dict):
                    continue

                # Provider already normalizes to {question, title, snippet, source}
                accumulated_results.append(item)

                if item.get("source"):
                    accumulated_sources.append(item.get("source"))

        except Exception as e:
            error_msg = f"Search failed for query '{q}': {str(e)}"
            accumulated_errors.append(error_msg)

    # Determine status
    status = "search_complete" if success_count > 0 else "search_failed"

    # LangGraph will use `operator.add` to append these results to the global state.
    # We increment the iteration count to maintain the loop safety valve.
    return {
        "search_results": accumulated_results,
        "sources": list(set(accumulated_sources)),
        "errors": accumulated_errors,
        "status": status,
        "iteration_count": current_iteration + 1
    }
